EEI story 2a
IBM/cp4i-deployment-samples pull request #136
Opened 2020-11-03 13:28 UTC by tim-lo

Post:
![image](https://user-images.githubusercontent.com/3327922/97990831-6b94fe00-1dd8-11eb-8429-c0f30c370fde.png)

Get:
![image](https://user-images.githubusercontent.com/3327922/97990843-718adf00-1dd8-11eb-9d53-bb5aeb469653.png)

2020-11-03 15:05 UTC, tim-lo commented
To-Do: populate claimStatus field in db-writer

2020-11-04 08:16 UTC, DanRoseus approved these changes
Looks good!

2020-11-04 09:41 UTC, hrizvi1 approved these changes
LGTM

2020-11-04 10:10 UTC, DanRoseus requested changes
Tracing should not be disabled

2020-11-04 10:10 UTC, DanRoseus commented on products/bash/release-ace-integration-server.sh
> +
```suggestion
```

2020-11-04 11:00 UTC, DanRoseus approved these changes
Looks good

2020-11-04 11:03 UTC, Kinshuk1993 approved these changes
looks good

2020-11-04 11:04 UTC, merged