Eei prereqs
IBM/cp4i-deployment-samples pull request #75
Opened 2020-08-24 15:55 UTC by laurensks

This pr addresses https://github.ibm.com/cp4i/icp4i-fermi/issues/96 and https://github.ibm.com/cp4i/icp4i-fermi/issues/97

2020-08-24 16:03 UTC, Kinshuk1993 commented
Logs for prereqs of ddd and eei ran twice: [prereqs-log.txt](https://github.com/IBM/cp4i-deployment-samples/files/5118967/eei-prereqs-log.txt)

2020-08-25 07:22 UTC, DanRoseus requested changes

2020-08-25 07:22 UTC, DanRoseus commented on DrivewayDentDeletion/Operators/prereqs.sh
> +fi  #${CURRENT_DIR}/../../products/bash/create-ocp-pipeline
```suggestion
fi  #${CURRENT_DIR}/../../products/bash/install-ocp-pipeline
```

2020-08-25 07:22 UTC, DanRoseus commented on DrivewayDentDeletion/Operators/prereqs.sh
>  oc -n ${test_namespace} policy add-role-to-user registry-editor system:serviceaccount:${dev_namespace}:image-bot
`image-bot` sounds like a general purpose service account and this permission is DDD specific. I guess this service account name should have `ddd` in it.

2020-08-25 07:22 UTC, DanRoseus commented on DrivewayDentDeletion/Operators/prereqs.sh
> +  name: postgres-credential
This credential is DDD specific, so should have `ddd` in it's name

2020-08-25 07:22 UTC, DanRoseus commented on DrivewayDentDeletion/Operators/prereqs.sh
> +  if ! ${CURRENT_DIR}/../../products/bash/create-ace-config.sh -n ${image_project} -g $POSTGRES_NAMESPACE -u $DB_USER -d $DB_NAME -p $DB_PASS; then
I think this script is not really general purposes. It's creating an ACE `Configuration` that is specific to DDD, referring to the DDD MQ and the DDD postgres database. Maybe this should be in the DDD dir. And also use a name for the `Configuration` that includes `ddd` (currently it uses `ace-policyproject`).

2020-08-25 07:22 UTC, DanRoseus commented on EventEnabledInsurance/prereqs.sh
> +while getopts "n:r:" opt; do
```suggestion
while getopts "n:" opt; do
```
`r` option is not used

2020-08-25 07:22 UTC, DanRoseus commented on EventEnabledInsurance/prereqs.sh
> +if ! ${CURRENT_DIR}/../products/bash/create-ocp-pipeline.sh; then
```suggestion
if ! ${CURRENT_DIR}/../products/bash/install-ocp-pipeline.sh; then
```
As above

2020-08-25 07:22 UTC, DanRoseus commented on products/bash/configure-postgres.sh
> +#     ./configure-postgres.sh
Maybe call this `create-postgres-db.sh`?

2020-08-25 07:22 UTC, DanRoseus commented on products/bash/configure-postgres.sh
> +
I think `DB_PASS` should not be optional. Make this error if `DB_PASS` is not passed or is blank.

2020-08-25 07:22 UTC, DanRoseus commented on products/bash/entitled-registry.sh
> +cat << EOF | oc apply --namespace ${namespace} -f -
I think this secret is only used for a pipeline service account? Maybe this could be moved to `configure-ocp-pipeline.sh`?

2020-08-25 07:22 UTC, DanRoseus commented on DrivewayDentDeletion/Operators/prereqs.sh
> +  echo -e "INFO: Configuring postgres in the '$image_project' namespace with the user '$DB_USER' and database name '$DB_NAME' and suffix '$SUFFIX'\n"
The `$image_project` doesn't really matter here, all it's doing is creating a database in the postgres instance that could be accessed from anywhere. Also not sure the suffix is relevant. Suggest changing to:
```suggestion
  echo -e "INFO: Creating '$DB_NAME' database and '$DB_USER' user in the postgres instance in the ${POSTGRES_NAMESPACE} namespace\n"
```

2020-08-26 14:32 UTC, laurensks commented
Successful pipelines: 
![image](https://user-images.githubusercontent.com/67965358/91316933-52a51680-e7b1-11ea-8e96-b56d93570e14.png)

![image](https://media.github.ibm.com/user/246532/files/25f0ff00-e7b1-11ea-91b2-497399c9c227)

2020-08-26 14:49 UTC, laurensks commented
[e2e-logs.txt](https://github.com/IBM/cp4i-deployment-samples/files/5130559/prereqs-logs.txt)

2020-08-26 14:50 UTC, Kinshuk1993 commented
1-click run log: 
[1-click-run-log.txt](https://github.com/IBM/cp4i-deployment-samples/files/5130568/1-click-run-log.txt)

2020-08-27 12:54 UTC, DanRoseus approved these changes
Looks good!

2020-08-27 12:55 UTC, merged